org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# Disable SSL verification to fix "Tag mismatch" errors
systemProp.javax.net.ssl.trustStore=NONE
systemProp.javax.net.ssl.trustStoreType=Windows-ROOT
org.gradle.internal.http.socketTimeout=120000
org.gradle.internal.http.connectionTimeout=120000
